name: format, lint & type check

on: [pull_request]

jobs:
  format-lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-node@v2-beta
      - name: Install dependencies
        run: yarn
        working-directory: .
      - name: Format
        run: yarn format:check
        working-directory: .
      - name: Lint
        run: yarn lint
        working-directory: .
      - name: TypeCheck
        run: npm run type:check
        working-directory: .
